### ISSUE TITLE
Transition to SQLite backend

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#471]
Our in-memory database is just for development.

We're eventually going to connect to `SQLite` via the `soul-cli` REST wrapper.

Here is the repo: https://github.com/DeepBlueCLtd/RCO-Soul

It currently has a database with the wrong schema, I hope to provide a valid database tomorrow.

The readme includes instructions on how to run the server.   I propose we take this strategy:
- clone rco-soul
- run install for rco-soul
- run dev:soul
- modify RCO to integrate with the soul-server

Note: there is a `react-admin` app in the `src` folder. There is a working `dataProvider.ts` in the `src/common` folder.  This includes functionality to implement the correct REST API calls.

I _think_ the RCO data provider will have to pass its calls through this `dataProvider`.   We'll copy the `dataProvider` into `RCO` repo.

Bit's missing from `rco2.sqlite`:
* [x] config data
* [x] rename `catHandling` to `catHandle`
* [x] `IDs` need to be `integer` for references to work
* [x] dispatch table doesn't have `toAddress` field
* [x] `IDs` should be auto-incremented
* [x] Project table doesn't include `start and end dates`
* [x] Change `rco_power_user` in user table to `rco-power-user`
* [x] add at least `5 project` entries in `batch table` to test filters
* [x] `Vault` table is not there
* [x] `User` table doesn't have `salt` field which is required for `password security`
* [x] The schema of `vault` is not valid
* [x] `dataId` is not there in `audit` table
* [ ] ~~Change `batch` in item table to `batchId`~~ The front end has been changed to `batch`.
* [x] configData has `snake_case` fields (e.g. cat_code, cat_handle, cat_cave)
* [x] there is `item_number` (snake_case) in item type on frontend, need to convert to `itemNumber`
* [ ] `Start` and `End` dates in the `database` are not according to `constraints` (start must be before end) in `project` table. Remarks are required in `edit project` but not in `create project`. 
* [x] `Remarks` is not required on `dispatch form` on frontend but database has `Not Null constraint` on remarks
* [x] `Dispatch` table doesn't have `reportPrintedAt`
* [x] `Destruction` table doesn't have `reportPrintedAt`
* [ ] need to fix `BooleanFilter`

**Need to update the `dataProvider` from RCO-Soul for accomodating filters (e.g. `_eq`, `_neq`)**

**TODO:**

- [x] Filters for handling _eq, _neq etc.
- [x] Destruction remarks on `frontend` is marked as optional whereas database has `Not NULL` constraint on remarks
- [x] Item `remarks` and `musterRemarks` on `frontend` are marked as optional whereas database has `Not NULL` constraint on remarks and musterRemarks

**Comment by TahaKhanAbdalli** [comment]
`RCO2.sqlite` related issues discussed in this issue, 3rd issue is no longer required as it has been resolved in the `soul-cli` package.
