### ISSUE TITLE
installation investigations

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#723]
* [x] Storing IP address in audit log

## Changes
* [x] Make `role` in `user` table nullable
* [x] Update [loanUsers](https://github.com/DeepBlueCLtd/RCO/issues/812) VIEW  to include field names
* [x] Make DISPATCH.Name and DESTRUCTION.Name optional (so they can be generated in afterCreate)
* [x] Introduce `VAULT` to `richItem`
* [x] disable current default ORG, set it to AD
* [x] enable department for RAF analysis
* [x] introduce `departement` to `richItem`
* [x] amend `loanUsers` to provide `id` field and show `staffNumber`
* [x] amend `users` to introduce `lastUpdatedAt` and `lockoutAttempts`
* [x] wipe new security database
* [x] clear status for two dispatches (17 and 18)
* [x] check items recently added to legacy batches
* [x] update loanUsers
* [x] remove foreign key on item.VaultLocation (since it's optional)

## Inspect
* [x] View issue with adding a Vault with Megan
* [x] View process for user muster list. Capture terms/names in #838
* [x] Format of batch, dispatch, destruction reference numbers. 
* [x] What data do we have to determine new destruction IDs?
* [x] Create new config values for `headerMarking` and `reportPrefix`
* [x] Check display of items from old vaults
* [x] Trial generation of dispatches, items, batches, destructions (once new id generation is in place)
* [x] Examine history for completed dispatches
* [x] Check for presence of VAULT/LEGACY in past destructions/dispatches.  We need to reflect that data, but we will just use `VAULT` in the future.  Do we need to add this stored field in destruction/dispatch tables?
* [x] Check format of departed date in `user` table.  Check SQLite/JS mock data matches this pattern. (#788 ) **Update:** it's like `2009-08-01 00:00:00`. But if we mark the user as departed, the value is in ISO date-time format.
* [x] Check display of legacy dispatches & destructions, is the vault name already in the title?
* [ ] inspect why edited item isn't clickable (#925)

## With valid data
* [x] View items, all items
* [x] Filter items
* [x] Welcome page content (pending returns?, loans)
* [x] Run through dispatch/destruction.  Check data edits.
* [x] Have we populated `loanedTo` in `items`, or do we need to get it from audit log?

**Comment by IanMayo** [comment]
Done.
